ingress:
  enabled: ${ingress_enable}
  host: ${jsonencode(ingress_host)}
  annotations:
    ${indent(4, yamlencode(merge({
      "alb.ingress.kubernetes.io/scheme"               = "internet-facing"
      "alb.ingress.kubernetes.io/ip-address-type"      = "ipv4"
      "alb.ingress.kubernetes.io/target-type"           = "ip"
      "alb.ingress.kubernetes.io/backend-protocol"      = "HTTP"
      "alb.ingress.kubernetes.io/listen-ports"          = "[{\"HTTP\":80},{\"HTTPS\":443}]"
      "alb.ingress.kubernetes.io/ssl-redirect"          = "443"
      "alb.ingress.kubernetes.io/ssl-policy"            = "ELBSecurityPolicy-TLS13-1-2-2021-06"
      "alb.ingress.kubernetes.io/healthcheck-path"      = "/health"
      "alb.ingress.kubernetes.io/healthcheck-port"      = "traffic-port"
      "alb.ingress.kubernetes.io/healthcheck-protocol"  = "HTTP"
      "alb.ingress.kubernetes.io/success-codes"         = "200"
    }, ingress_annotations)))}
